### ISSUE TITLE
Please, help!

### ISSUE THREAD

**Issue by crazychaz** [krsnik93/plugin-chart-status-indicator#6]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sections')
    at eval (controlPanel.tsx:13:5)
    at ./src/controlPanel.tsx (main.js:73:1)
    at __webpack_require__ (main.js:184:41)
    at eval (chart.ts:7:71)
    at ./src/chart.ts (main.js:51:1)
    at __webpack_require__ (main.js:184:41)
    at eval (entry.ts:2:64)
    at ./src/entry.ts (main.js:84:1)
    at __webpack_require__ (main.js:184:41)
    at main.js:236:37

**Comment by krsnik93** [comment]
Hey, I am not maintaining this anymore, but will accept PRs and review them quickly.
